Midterm/ConsultingWebsite/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ConsultingWebsite.Models
{
    public class Employee
    {
        [Key]
        public int Emp_No { get; set; }

        [Display(Name = "First Name")]
        [MaxLength(24, ErrorMessage = "Name is too long")]
        [Required]
        public string First_Name { get; set; }

        [Display(Name = "Last Name")]
        [MaxLength(30, ErrorMessage = "Name is too long")]
        [Required]
        public string Last_Name { get; set; }

        [Display(Name = "Title")]
        [MaxLength(3, ErrorMessage = "Mr/Mrs")]
        [Required]
        public string Title { get; set; }

        [Display(Name = "Phone #")]
        [DataType(DataType.PhoneNumber)]
        [Required]
        [MaxLength(14)]
        [RegularExpression(@"^(1-)?(\d{3}|\(\d{3}\) )-?\d{3}-?\d{4}$",
            ErrorMessage = "Invalid phone number")]
        public string Phone_No { get; set; }

        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [Required]
        public string Email { get; set; }

        [Display(Name = "Street Address 1")]
        [Required]
        [StringLength(100)]
        [MinLength(3)]
        public string Street_Address1 { get; set; }

        [Display(Name = "Street Address 2")]
        [StringLength(10)]
        [MinLength(1)]
        public string Street_Address2 { get; set; }

        [Display(Name = "City")]
        [StringLength(30)]
        public string City { get; set; }

        [Display(Name = "State")]
        [MinLength(2)]
        public string State { get; set; }

        [Display(Name = "Zip Code")]
        [DataType(DataType.PostalCode)]
        [StringLength(10)]
        [MinLength(5)]
        [Required]
        public string Zip_Code { get; set; }

        [NotMapped]
        public string Full_Name
        {
            get { return First_Name + Last_Name; }
        }
        [NotMapped]
        public string Mailing_Address
        {
            get { return Street_Address1 + Street_Address2; }
        }

        // Navigation
        [ForeignKey("Emp_No")]
        public virtual IList<Job> Jobs { get; set; }
    }
}

Midterm/ConsultingWebsite/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConsultingWebsite.Models;
using ConsultingWebsite.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PagedList;

namespace ConsultingWebsite.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private ConsultingDbContext db = new ConsultingDbContext();

        // GET: Employees
        public ActionResult Index(
            string search,
            string sortBy,
            int? page,
            int? itemsPerPage)
        {
            var emps =
                from e in db.Employees
                orderby e.Emp_No
                select new EmployeeInfo
                {
                    Emp_No = e.Emp_No,
                    First_Name = e.First_Name,
                    Last_Name = e.Last_Name,
                    Title = e.Title,
                    Phone_No = e.Phone_No,
                    Email = e.Email,
                    Street_Address1 = e.Street_Address1,
                    Street_Address2 = e.Street_Address2
                };


            if (!User.IsInRole("Administrator") || !User.IsInRole("HR"))
            {
                var userId = HttpContext.User.Identity.GetUserId();
                var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                var user = userManager.FindById(userId);

                var employee = (
                    from e in db.Employees
                    where e.Emp_No == user.emp_no
                    select e.Emp_No).FirstOrDefault();

                emps = emps.Where(x => x.Emp_No == employee);
            }
            if (!string.IsNullOrEmpty(search))
            {
                emps = emps.Where(x => x.Last_Name.Contains(search) || x.First_Name.Contains(search));
            }

            switch (sortBy)
            {
                default:
                    emps = emps.OrderBy(e => e.Emp_No);
                    break;
                case "Employee #":
                    emps = emps.OrderBy(e => e.Emp_No);
                    break;
                case "Last Name":
                    emps = emps.OrderBy(e => e.Last_Name);
                    break;
                case "First Name":
                    emps = emps.OrderBy(e => e.First_Name);
                    break;
            }

            var model = new EmployeeSearchResults
            {
                Search = search,
                SortBy = sortBy,
                Results = emps.ToPagedList(page ?? 1, itemsPerPage ?? 5)
            };

            ViewBag.Search = search;

            return View("Index", model);
        }

        // GET: Employees/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            var userId = HttpContext.User.Identity.GetUserId();
            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.FindById(userId);

            Employee loggedInUser = db.Employees.FirstOrDefault(x => x.Emp_No == user.emp_no);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(loggedInUser);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "HR,Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Emp_No,First_Name,Last_Name,Title,Phone_No,Email,Street_Address1,Street_Address2,City,State,Zip_Code")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Emp_No,First_Name,Last_Name,Title,Phone_No,Email,Street_Address1,Street_Address2,City,State,Zip_Code")] Employee employee)
        {
            if (!User.IsInRole("Administrator") && !User.IsInRole("HR"))
            {
                var userId = HttpContext.User.Identity.GetUserId();
                var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                var user = userManager.FindById(userId);

                Employee loggedInUser = db.Employees.FirstOrDefault(x => x.Emp_No == user.emp_no);

                if (ModelState.IsValid)
                {
                    db.Entry(loggedInUser).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(loggedInUser);
            }
            else if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        [Authorize(Roles = "Administrator,HR")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "HR,Administrator")]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Midterm/ConsultingWebsite/Views/Employees/Create.cshtml
@model ConsultingWebsite.Models.Employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.First_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.First_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.First_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Last_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Last_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Last_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street_Address1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street_Address1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street_Address1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street_Address2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street_Address2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street_Address2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Midterm/ConsultingWebsite/Views/Employees/Delete.cshtml
@model ConsultingWebsite.Models.Employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.First_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.First_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Last_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Last_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street_Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street_Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street_Address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street_Address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip_Code)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Midterm/ConsultingWebsite/Views/Employees/Details.cshtml
@model ConsultingWebsite.Models.Employee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.First_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.First_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Last_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Last_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street_Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street_Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street_Address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street_Address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip_Code)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Emp_No }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Midterm/ConsultingWebsite/Views/Employees/Edit.cshtml
@model ConsultingWebsite.Models.Employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Emp_No)

        <div class="form-group">
            @Html.LabelFor(model => model.First_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.First_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.First_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Last_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Last_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Last_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street_Address1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street_Address1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street_Address1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street_Address2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street_Address2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street_Address2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Midterm/ConsultingWebsite/Views/Employees/Index.cshtml
@model ConsultingWebsite.ViewModels.EmployeeSearchResults
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";

    bool isHr = Request.IsAuthenticated && User.IsInRole("HR");
    bool isManager = Request.IsAuthenticated && User.IsInRole("Administrator");
    bool isContractor = Request.IsAuthenticated && User.IsInRole("Contractor");
}

<h2>Employees</h2>

@{
    using (Html.BeginForm("Index", "Employees", FormMethod.Get))
    {
        var sortByArray = new SelectListItem[]
        {
            new SelectListItem { Value = "emp_no", Text = "Employee #" },
            new SelectListItem { Value = "Last_Name", Text = "Last Name" },
            new SelectListItem { Value = "First_Name", Text = "First Name" }
        };
        var sortByList = new SelectList(sortByArray, "Value", "Text");

        <div class="mb-3">
            <input class="btn btn-primary" type="submit" value="Apply" />
        </div>
    }
}

@if (isHr)
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table">
    <tr>
        <th>Emp #</th>
        <th>Name</th>
        <th>Title</th>
        <th>Phone #</th>
        <th>Email</th>
        <th>Mailing Address</th>
        <th></th>
    </tr>

    @foreach (var item in Model.Results)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Emp_No)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Full_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone_No)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mailing_Address)
            </td>

            @if (isHr)
            {
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Emp_No }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Emp_No })
                </td>
            }
            @if (isHr || isContractor)
            {
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Emp_No })
                </td>
            }
        </tr>
    }
</table>
<div>
    @Html.PagedListPager(
        Model.Results,
        page => Url.Action("Index", new
        {
            Search = Model.Search,
            SortBy = Model.SortBy,
            Page = page,
            ItemsPerPage = Model.Results.PageSize,
        }),
        new PagedListRenderOptions
        {
            Display = PagedListDisplayMode.IfNeeded,
            DisplayPageCountAndCurrentLocation = true,
            DisplayEllipsesWhenNotShowingAllPageNumbers = true,
            MaximumPageNumbersToDisplay = 5,
            PageCountAndCurrentLocationFormat = "Page {0} of {1}"
        }
    )
</div>